// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmoothAiProductContextMemory.Infrastructure.Persistence;

#nullable disable

namespace SmoothAiProductContextMemory.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SmoothAiProductContextMemoryDbContext))]
    partial class SmoothAiProductContextMemoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmoothAiProductContextMemory.Domain.Entities.GroupDescription", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_on")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("GroupId")
                        .HasColumnType("bigint")
                        .HasColumnName("group_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("GroupId", "Version")
                        .IsUnique();

                    b.ToTable("group_description", (string)null);
                });

            modelBuilder.Entity("SmoothAiProductContextMemory.Domain.Entities.Initiative", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("initiative", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "Default initiative for groups not yet assigned.",
                            Name = "to-be-decided",
                            Status = "active"
                        });
                });

            modelBuilder.Entity("SmoothAiProductContextMemory.Domain.Entities.Label", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("label", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 2L,
                            Name = "positioning",
                            Status = "active"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "architecture",
                            Status = "active"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "storage",
                            Status = "active"
                        },
                        new
                        {
                            Id = 5L,
                            Name = "domain-model",
                            Status = "active"
                        },
                        new
                        {
                            Id = 6L,
                            Name = "write-path",
                            Status = "active"
                        },
                        new
                        {
                            Id = 7L,
                            Name = "retrieval",
                            Status = "active"
                        },
                        new
                        {
                            Id = 8L,
                            Name = "security",
                            Status = "active"
                        },
                        new
                        {
                            Id = 9L,
                            Name = "governance",
                            Status = "active"
                        },
                        new
                        {
                            Id = 10L,
                            Name = "prior-art",
                            Status = "active"
                        },
                        new
                        {
                            Id = 11L,
                            Name = "process",
                            Status = "active"
                        });
                });

            modelBuilder.Entity("SmoothAiProductContextMemory.Domain.Entities.Memory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.PrimitiveCollection<List<string>>("Facets")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("facets");

                    b.Property<long>("GroupId")
                        .HasColumnType("bigint")
                        .HasColumnName("group_id");

                    b.Property<Guid>("LineageId")
                        .HasColumnType("uuid")
                        .HasColumnName("lineage_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("SubjectSlug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("subject_slug");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Facets");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Facets"), "gin");

                    b.HasIndex("LineageId");

                    b.HasIndex("Tags");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Tags"), "gin");

                    b.HasIndex("Uuid")
                        .IsUnique();

                    b.HasIndex("GroupId", "SubjectSlug")
                        .IsUnique();

                    b.ToTable("memory", (string)null);
                });

            modelBuilder.Entity("SmoothAiProductContextMemory.Domain.Entities.MemoryGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_on")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("InitiativeId")
                        .HasColumnType("bigint")
                        .HasColumnName("initiative_id");

                    b.Property<string>("Repo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("repo");

                    b.Property<string>("RepoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("repo_url");

                    b.Property<string>("ScopeDimension")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("scope_dimension");

                    b.Property<string>("ScopeIdentifier")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("scope_identifier");

                    b.Property<string>("Tickets")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("tickets");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InitiativeId");

                    b.HasIndex("Tickets");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Tickets"), "gin");

                    b.HasIndex("Uuid")
                        .IsUnique();

                    b.ToTable("memory_group", (string)null);
                });

            modelBuilder.Entity("SmoothAiProductContextMemory.Domain.Entities.MemoryLink", b =>
                {
                    b.Property<long>("SourceMemoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("source_memory_id");

                    b.Property<long>("TargetMemoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("target_memory_id");

                    b.Property<string>("Relation")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("relation");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.HasKey("SourceMemoryId", "TargetMemoryId", "Relation");

                    b.HasIndex("TargetMemoryId");

                    b.ToTable("memory_link", (string)null);
                });

            modelBuilder.Entity("SmoothAiProductContextMemory.Domain.Entities.MemoryVersion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BlobAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("blob_address");

                    b.Property<short>("Confidence")
                        .HasColumnType("smallint")
                        .HasColumnName("confidence");

                    b.Property<string>("ContentSummary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_summary");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_on")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_current");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("kind");

                    b.Property<long>("MemoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("memory_id");

                    b.Property<string>("Sources")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("sources");

                    b.Property<string>("Statement")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("statement");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("timestamptz")
                        .HasColumnName("valid_from");

                    b.Property<DateTimeOffset?>("ValidUntil")
                        .HasColumnType("timestamptz")
                        .HasColumnName("valid_until");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Kind");

                    b.HasIndex("MemoryId")
                        .IsUnique()
                        .HasFilter("\"is_current\"");

                    b.HasIndex("Status");

                    b.HasIndex("MemoryId", "Version")
                        .IsUnique();

                    b.ToTable("memory_version", (string)null);
                });

            modelBuilder.Entity("SmoothAiProductContextMemory.Domain.Entities.GroupDescription", b =>
                {
                    b.HasOne("SmoothAiProductContextMemory.Domain.Entities.MemoryGroup", "Group")
                        .WithMany("Descriptions")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("SmoothAiProductContextMemory.Domain.Entities.Memory", b =>
                {
                    b.HasOne("SmoothAiProductContextMemory.Domain.Entities.MemoryGroup", "Group")
                        .WithMany("Memories")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("SmoothAiProductContextMemory.Domain.Entities.MemoryGroup", b =>
                {
                    b.HasOne("SmoothAiProductContextMemory.Domain.Entities.Initiative", "Initiative")
                        .WithMany()
                        .HasForeignKey("InitiativeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Initiative");
                });

            modelBuilder.Entity("SmoothAiProductContextMemory.Domain.Entities.MemoryLink", b =>
                {
                    b.HasOne("SmoothAiProductContextMemory.Domain.Entities.Memory", "SourceMemory")
                        .WithMany("LinksFrom")
                        .HasForeignKey("SourceMemoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmoothAiProductContextMemory.Domain.Entities.Memory", "TargetMemory")
                        .WithMany("LinksTo")
                        .HasForeignKey("TargetMemoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceMemory");

                    b.Navigation("TargetMemory");
                });

            modelBuilder.Entity("SmoothAiProductContextMemory.Domain.Entities.MemoryVersion", b =>
                {
                    b.HasOne("SmoothAiProductContextMemory.Domain.Entities.Memory", "Memory")
                        .WithMany("Versions")
                        .HasForeignKey("MemoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Memory");
                });

            modelBuilder.Entity("SmoothAiProductContextMemory.Domain.Entities.Memory", b =>
                {
                    b.Navigation("LinksFrom");

                    b.Navigation("LinksTo");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("SmoothAiProductContextMemory.Domain.Entities.MemoryGroup", b =>
                {
                    b.Navigation("Descriptions");

                    b.Navigation("Memories");
                });
#pragma warning restore 612, 618
        }
    }
}
